### ISSUE TITLE
Uppdatera form-applications.client.view.html

### ISSUE THREAD

**Issue by saraC15** [careerfairsystems/studentsession#3]
Lägg till input för att kunna skicka med:

Vilka företag användaren söker kontaktsamtal med.
Vilka tider användaren KAN, obs bindande (8-10, 10-12, 13-15 osv för alla dagar
Skicka CV (Tar endast emot PDF pdf)
Telefon och email

**Grundläggande**
- [x] Lägg till så att CV kan laddas upp
- [x] Gör kompletta felmeddelanden för obligatoriska fält

**Cv-uppladdning**
- [x] Lägg till url till pdf:n i databasen när pdf laddas upp
- [x] Lägg till så att CV kan laddas upp på svenska och/eller engelska
- [ ] Lägg till så att användaren kan se namnet på den fil som _valts_.
- [x] Gör så att "Lämna in cv"-knappen döljs när man lämnat in ett cv, syns igen om man trycker på ångra och texten "Ditt cv har laddats upp!" då försvinner.
- [ ] Lägg till felmeddelande för om filen är för stor eller fel format.

**Kontaktsamtalskoordinatorn**
Gör så att kontaktsamtalskoordinatorn kan...
- [x] Ändra vilka tider/tidsintervall som kan väljas
- [ ] Ändra introtext
- [ ] Ange när formuläret ska visas
- [x] Ange max antal ord i "om mig"

**Text**
- [x] Ändra till genomgående formuleringar (liknande på hela hemsidan)

**Formatering**
- [ ] Alla textrutor/selectboxes till samma stil
- [ ] Alla rutor/textområden till samma längd
- [ ] Byt till en snyggare lösning för att förhindra för lång inmatning i "om mig" (nuvarande lösning tar bort det som är på slutet av strängen, oberoende av var i strängen man skriver. Inte snyggt om man inte skriver i slutet av strängen. Bättre: förhindra annan inmatning än delete/backspace när maximal längd på stängen nåtts.)

**Comment by saraC15** [comment]
**Framtida tillägg till detta** (dela upp issues!)

Kontaktsamtalskoordinatorn
- Ändra vilka tider/tidsintervall som kan väljas
- Ändra introtext
- Ange när formuläret ska visas
- Ange max antal ord i "om mig"

Text
- Ändra till genomgående formuleringar (liknande på hela hemsidan)
- Felmeddelanden även för om företag och/eller tid inte valts

Formatering
- Alla textrutor/selectboxes har inte samma stil
- Vissa rutor/textområden går ut i kanten, andra är mycket kortare

Gäst
- Lägga till en gästsida som uppmanar till inloggning (just nu kommer en helt tom drop-down meny ned för gäster)

**Comment by xNilsson** [comment]
Här är ett tips på hur man kan dela upp en issue i mindre tasks! :)
https://github.com/blog/1375-task-lists-in-gfm-issues-pulls-comments @saraC15  @NilssonJohan

**Comment by saraC15** [comment]
Åh toppen - tack :D @cNille
